### PR TITLE
fix boolean escape and quotes

### LINKED ISSUE #92: booleans quoted even when they are keys
```
"y": 2
```

I think this is wrong thing to do with **keys**. https://github.com/dtolnay/serde-yaml/pull/83#discussion_r152628088

### PR DESCRIPTION
**Pull request by chyh1990**
Fix #92 

@hoodie  looks good?

### CODE REVIEW

File: src/emitter.rs [hunk 1]
```diff
@@ -425,7 +428,7 @@ products:
   "true": bool key
   "{}": empty hash key
 x: test
-"y": "can't avoid quoting here"
+y: "can't avoid quoting here"
```
Comment (hoodie) [inline src/emitter.rs]: it still says "can't avoid quoting here", which contradicts this change

File: src/yaml.rs [hunk 2]
```diff
@@ -310,8 +310,9 @@ impl Yaml {
         }
         match v {
             "~" | "null" => Yaml::Null,
-            "true" => Yaml::Boolean(true),
-            "false" => Yaml::Boolean(false),
+            // http://yaml.org/type/bool.html
+            "true" | "True" | "TRUE" | "yes" | "Yes" | "YES" | "on" | "On" | "ON" => Yaml::Boolean(true),
```
Comment (hoodie) [inline src/yaml.rs]: this would introduce a regression, your [link](http://yaml.org/type/bool.html) points to the 1.1 spec, but this is supposed to be a yaml1.2 library. In 1.2 all of these keywords nolonger become bools but strings.
http://www.yaml.org/spec/1.2/spec.html#id2803629

Comment (hoodie) [reply src/yaml.rs]: unless you want to add an explicit `1.1` mode perhapse, yaml has the attribute `%Yaml 1.1` in line 1 before `---`

**Comment by regexident** [comment]
As a user relying on reading the crate description (which states conformance to 1.2) I too would expect **yaml-rust** to behave according to the 1.2 specs. 🤔

**Comment by hoodie** [comment]
@regexident apparently libs like libyaml are already sloppy in that regard, parsing `y: no` as `"y": false`. I would suggest regarding the `%YAML 1.x` directive and acting accordingly, but yaml1.1 is a much larger standard then 1.2

File: src/emitter.rs (hunk 1 above)
Comment (hoodie) [reply src/emitter.rs]: if it's the different treatment of say `"y": ...` and `x: ...`, why don't we just quote all keys in the export format? it's still valid yaml

**Comment by chyh1990** [comment]
@hoodie I've reverted changes regarding to the parser. I know not quoting 'y'/'Y'/'n'/'N' is violating YAML 1.1 spec, but libyaml/ruby/PyYAML are already doing this (without emitting `%YAML 1.x`).
And it conforms to YAML 1.2 anyway.
